
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: promptflow-1ES-win

steps:
- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  inputs:
    sourceScanPath: ../../src/
  displayName: 'Component Detection'
